twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        dev_contact_mail: 'contact@code-rocket-ideas.fr'
        dev_contact_git: 'https://github.com/FloNoobDev'
        
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
